### ISSUE TITLE
请问可以提供Mac App Store版本的微信吗

### ISSUE THREAD

**Issue by Soindigo** [zsbai/wechat-versions#1]
最后一个非内置浏览器的3.7.0版本，如果有在访达「应用程序」中有「微信.app」，可以打包一下吗。谢谢

**Comment by zsbai** [comment]
release中提供了3.7.0的版本，是从官网下载的，应该和app store版本的没有区别吧？

**Comment by Soindigo** [comment]
> release中提供了3.7.0的版本，是从官网下载的，应该和app store版本的没有区别吧？

app store的版本有沙箱保护，而且少了一些像检查更新的插件等。

**Comment by zsbai** [comment]
> > release中提供了3.7.0的版本，是从官网下载的，应该和app store版本的没有区别吧？
> 
> 
> 
> app store的版本有沙箱保护，而且少了一些像检查更新的插件等。

明白了，但是我并没有保存苹果商店的版本，没有直链下载起来很不方便😂你可以在网上再找找

**Comment by Soindigo** [comment]
> 

非常难找呢，一是app store下载结束后会删除安装包，二是mac app store有SSL pinning也无法抓包。不过还是谢谢啦，能保存这些版本也很棒，不好容易找到。微信这种流氓不提供更新日志不提供老版本下载真的很烦。

**Comment by zsbai** [comment]
> > 
> 
> 非常难找呢，一是app store下载结束后会删除安装包，二是mac app store有SSL pinning也无法抓包。不过还是谢谢啦，能保存这些版本也很棒，不好容易找到。微信这种流氓不提供更新日志不提供老版本下载真的很烦。

是的 之前真的很难找微信老版本的安装包 看到别人的windows微信保存项目就搞了一个Mac的😊

**Comment by standerXon** [comment]
你们是怎么登录的呀，手机扫码登录老版本微信自动升级了（丢）
